from typing import Protocol, runtime_checkable


@runtime_checkable
class Broker(Protocol):
    async def submit_order(self, order: dict) -> dict: ...

    async def cancel_order(self, order_id: str) -> bool: ...

    async def portfolio(self) -> dict: ...

    async def positions(self) -> list[dict]: ...
