from typing import Protocol, runtime_checkable


@runtime_checkable
class Store(Protocol):
    async def get(self, key: str) -> bytes | None: ...

    async def set(self, key: str, value: bytes) -> None: ...

    async def delete(self, key: str) -> None: ...

    async def exists(self, key: str) -> bool: ...

    async def list_keys(self, prefix: str) -> list[str]: ...
