from __future__ import annotations

from typing import Protocol
from uuid import UUID

from alpha_quant.contracts.operational import (
    AuditEvent,
    CandidateEvaluation,
    CorporateActionBooking,
    CurrentHalt,
    DecisionBatch,
    DecisionRun,
    FillBookingCommand,
    FillBookingResult,
    HaltCommand,
    PolicyEvaluation,
    PortfolioBook,
    PortfolioMark,
    PortfolioState,
    PositionCurrent,
    RiskEvent,
    RunReservation,
    Strategy,
)
from alpha_quant.domain.advice import AdviceArtifact
from alpha_quant.domain.risk import RiskPolicy


class OperationalStorePort(Protocol):
    def reserve_run(self, request: RunReservation) -> DecisionRun: ...
    def start_run(self, run_id: UUID) -> None: ...
    def complete_run(
        self, run_id: UUID, status: str, failure_reason: str | None = None
    ) -> None: ...
    def commit_decision_batch(self, batch: DecisionBatch) -> None: ...
    def book_fill(self, command: FillBookingCommand) -> FillBookingResult: ...
    def load_portfolio(self, book_id: UUID) -> PortfolioState: ...
    def save_portfolio_mark(self, mark: PortfolioMark) -> None: ...
    def set_halt(self, command: HaltCommand) -> None: ...
    def clear_halt(self, book_id: UUID) -> None: ...
    def current_halt(self, book_id: UUID) -> CurrentHalt | None: ...
    def rebuild_projections(self, book_id: UUID) -> None: ...
    def list_strategies(self) -> list[Strategy]: ...
    def list_books(self) -> list[PortfolioBook]: ...
    def list_decision_runs(self, book_id: UUID, limit: int = 20) -> list[DecisionRun]: ...
    def get_run_by_key(self, run_key: str) -> DecisionRun | None: ...
    def list_candidates(self, run_id: UUID, limit: int = 100) -> list[CandidateEvaluation]: ...
    def list_policy_evals(self, run_id: UUID, limit: int = 500) -> list[PolicyEvaluation]: ...
    def list_audit_events(self, run_id: UUID, limit: int = 200) -> list[AuditEvent]: ...
    def list_positions(self, book_id: UUID) -> list[PositionCurrent]: ...
    def load_risk_policy(self, version_label: str = "default") -> RiskPolicy | None: ...
    def save_risk_policy_version(self, policy: RiskPolicy) -> None: ...
    def write_risk_event(self, event: RiskEvent) -> None: ...
    def save_advice_artifact(self, advice: AdviceArtifact) -> str: ...
    def mark_explanations_stale(
        self, scope: str = "", scope_id: str = "", scorecard_id: str = ""
    ) -> int: ...
    def load_advice_artifacts(
        self, scope: str = "", scope_id: str = ""
    ) -> list[AdviceArtifact]: ...
    def write_corporate_action_booking(self, booking: CorporateActionBooking) -> None: ...
    def write_run_lock_audit(self, run_key: str, action: str) -> None: ...
